import {ArrowRight,CheckCircle2,Clock3,Sparkles,ShieldCheck} from 'lucide-react';
import PageHero from '../components/PageHero';
import Reveal from '../components/Reveal';
const services=[
 ['Recurring Cleaning','Keep your home consistently comfortable with a repeat schedule.',['Weekly, biweekly or monthly','Routine kitchen and bathroom care','Bedrooms, living areas and floors','Flexible priorities'],'/services/recurring-cleaning','https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=85'],
 ['Deep Cleaning','A detailed reset for homes that need extra attention.',['Detailed kitchen and bathroom work','Reachable detail areas and baseboards','Dusting, vacuuming and floors','Priority areas based on your home'],'/services/deep-cleaning','https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=1200&q=85'],
 ['Move In / Move Out','A transition-focused clean for an empty or changing home.',['Kitchen and appliances','Bathrooms and fixtures','Bedrooms and living spaces','Floors and high-touch areas'],'/services/move-in-move-out','https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=85'],
 ['Airbnb / Vacation Rental','Turnover-focused cleaning for guest-ready presentation.',['Guest-ready room reset','Kitchen and bathroom turnover','Linen/changeover coordination','Host-defined priorities'],'/services/airbnb-cleaning','https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=85']
];
export default function Services(){return <main><PageHero eyebrow="01 — SERVICES" title="Cleaning for" italic="every chapter." description="From routine upkeep to detailed resets and property turnovers, choose the service that fits your home." image="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=85"/><section className="section services"><Reveal><div className="centerHead"><div className="sectionLabel">A CLEAR SERVICE MENU</div><h2>Choose your <i>kind of clean.</i></h2><p>Each service has its own journey, scope and booking path. Select one to explore the details.</p></div></Reveal><div className="serviceGrid">{services.map((s,i)=><Reveal key={s[0]} delay={i*80}><article className="serviceCard"><div className="serviceImg"><img src={s[4]} alt={s[0]}/><span>0{i+1}</span></div><div className="serviceBody"><small>{s[0]}</small><h3>{s[0]}</h3><p>{s[1]}</p><ul className="miniList">{s[2].map(x=><li key={x}><CheckCircle2 size={15}/>{x}</li>)}</ul><a href={s[3]}>Explore service <ArrowRight size={17}/></a></div></article></Reveal>)}</div></section><section className="section"><div className="statsRow"><div className="stat"><strong>01</strong><span>Choose a service</span></div><div className="stat"><strong>02</strong><span>Share home details</span></div><div className="stat"><strong>03</strong><span>Select timing</span></div><div className="stat"><strong>04</strong><span>Confirm the request</span></div></div></section><section className="section softSection"><div className="center"><div className="sectionLabel" style={{justifyContent:'center'}}>THE LUMIÈRE STANDARD</div><h2>Thoughtful service, <i>beautifully organized.</i></h2><p>Use the booking flow for a tailored request, then connect final pricing, availability and service-area rules during production setup.</p><a className="btn gold" href="/book">Start a booking <ArrowRight size={17}/></a></div></section></main>}
