"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,CalendarDays,Check,ChevronDown,ChevronLeft,ChevronRight,Clock3,CircleCheck,HeartHandshake,Home as HomeIcon,MapPin,MessageCircle,Phone,ShieldCheck,Sparkles} from "lucide-react";
import Reveal from "./components/Reveal";

const heroSlides=[
 {image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2200&q=90',kicker:'THOUGHTFUL CLEANING. BEAUTIFUL HOMES.',title:'Come home to',italic:'something beautiful.',text:'Professional home cleaning with a more considered approach — dependable service, thoughtful details and a home you’ll love walking back into.'},
 {image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2200&q=90',kicker:'A HIGHER STANDARD OF CARE',title:'Your space,',italic:'beautifully cared for.',text:'From everyday upkeep to detailed resets, every visit is shaped around clarity, consistency and the details that make a home feel lighter.'},
 {image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=90',kicker:'SIMPLE. POLISHED. PERSONAL.',title:'A better clean',italic:'starts here.',text:'Choose your service, set your preferences and request a time through a booking journey designed to feel effortless.'}
];
const services=[
 {title:"Recurring Home Cleaning",tag:"Weekly • Biweekly • Monthly",desc:"A consistent, comfortable clean on the schedule that works for you.",href:"/services/recurring-cleaning",img:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=85"},
 {title:"Deep Cleaning",tag:"Detailed reset",desc:"A considered top-to-bottom reset for spaces that need extra attention.",href:"/services/deep-cleaning",img:"https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=1200&q=85"},
 {title:"Move In / Move Out",tag:"Transition cleaning",desc:"A thorough clean designed to help a home feel ready for its next chapter.",href:"/services/move-in-move-out",img:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=85"},
 {title:"Airbnb / Vacation Rental",tag:"Guest-ready turnovers",desc:"Turnover-focused cleaning for hosts who value dependable presentation.",href:"/services/airbnb-cleaning",img:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=85"}
];
const faqs=[['What cleaning services do you offer?','Recurring house cleaning, deep cleaning, move-in/move-out cleaning and Airbnb or vacation-rental turnover are presented as the core service paths.'],['How do recurring plans work?','Customers can choose weekly, biweekly or monthly service and share preferred timing through the booking flow.'],['Can I request a quote before booking?','Yes. The estimate tool uses home type, bedrooms, bathrooms and frequency to provide an on-screen planning estimate before the booking form.'],['What should I do before the cleaner arrives?','Use the cleaning checklist to review preparation guidance and make priorities clear before the appointment.'],['Can I book a move-out or rental turnover?','Yes. Dedicated service pages provide the correct starting point and connect directly to the booking flow.']];

export default function HomePage(){
 const [home,setHome]=useState('House'),[beds,setBeds]=useState('2'),[baths,setBaths]=useState('2'),[freq,setFreq]=useState('One time'),[faq,setFaq]=useState(0),[zip,setZip]=useState(''),[toast,setToast]=useState(''),[slide,setSlide]=useState(0);
 const estimate=useMemo(()=>{let n=89+(+beds-1)*18+(+baths-1)*12;if(home==='Apartment')n-=8;if(home==='Condo')n+=5;if(freq==='Weekly')n*=.9;if(freq==='Biweekly')n*=.95;return Math.round(n)},[home,beds,baths,freq]);
 useEffect(()=>{const id=window.setInterval(()=>setSlide(v=>(v+1)%heroSlides.length),6500);return()=>window.clearInterval(id)},[]);
 const notify=(m)=>{setToast(m);window.clearTimeout(window.__lumToast);window.__lumToast=window.setTimeout(()=>setToast(''),2800)};
 return <main>
 {toast&&<div className="toast"><CircleCheck size={19}/>{toast}</div>}
 <section className="hero"><div key={heroSlides[slide].image} className="heroImage" style={{backgroundImage:`url(${heroSlides[slide].image})`}}/><div className="heroShade"/><div className="heroContent"><div className="eyebrow light"><Sparkles size={16}/> {heroSlides[slide].kicker}</div><h1 key={slide}>{heroSlides[slide].title}<br/><i>{heroSlides[slide].italic}</i></h1><p key={`p-${slide}`}>{heroSlides[slide].text}</p><div className="heroBtns"><a className="btn gold" href="#quote">Get an Instant Quote <ArrowRight size={19}/></a><a className="btn ghost" href="/services">Explore Services</a></div><div className="heroTrust"><div><span className="stars">★★★★★</span><strong>Premium service experience</strong><small>Designed around your home</small></div><div className="vline"/><div><ShieldCheck size={25}/><strong>Trust-led service</strong><small>Clear communication</small></div></div></div><div className="heroSlideCounter">0{slide+1} <span>/ 0{heroSlides.length}</span></div><div className="heroControls"><button type="button" onClick={()=>setSlide((slide-1+heroSlides.length)%heroSlides.length)} aria-label="Previous slide"><ChevronLeft/></button><div>{heroSlides.map((_,i)=><button type="button" key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`Go to slide ${i+1}`}/>)}</div><button type="button" onClick={()=>setSlide((slide+1)%heroSlides.length)} aria-label="Next slide"><ChevronRight/></button></div><div className=""> <span/></div></section>
 <section className="trustBar">{[[ShieldCheck,'Vetted professionals','Trustworthy, dependable service'],[HeartHandshake,'Thoughtful cleaning','Details that make a difference'],[CalendarDays,'Flexible scheduling','Weekly to one-time service'],[MessageCircle,'Easy communication','Quick help when you need it']].map(([I,a,b])=><div key={a}><I/><div><b>{a}</b><span>{b}</span></div></div>)}</section>
 <Reveal><section className="intro section"><div className="sectionLabel">THE LUMIÈRE STANDARD</div><div className="introGrid"><div><h2>More than clean.<br/><i>It feels different.</i></h2></div><div><p>Life is busy enough. Your home should feel like the place where everything slows down. Lumière brings a considered, dependable approach to home cleaning — so you can spend less time managing your space and more time enjoying it.</p><a className="textLink" href="/about">Discover our approach <ArrowRight size={18}/></a></div></div></section></Reveal>
 <section className="services section"><Reveal><div className="sectionTop"><div><div className="sectionLabel">OUR SERVICES</div><h2>Cleaning for <i>every chapter.</i></h2></div><a className="outlineBtn" href="/services">View all services <ArrowRight size={18}/></a></div></Reveal><div className="serviceGrid">{services.map((s,i)=><Reveal key={s.title} delay={i*80}><article className="serviceCard"><div className="serviceImg"><img src={s.img} alt={s.title}/><span>0{i+1}</span></div><div className="serviceBody"><small>{s.tag}</small><h3>{s.title}</h3><p>{s.desc}</p><a href={s.href}>Explore service <ArrowRight size={17}/></a></div></article></Reveal>)}</div></section>
 <section id="quote" className="quote"><Reveal><div className="quoteCopy"><div className="sectionLabel light">YOUR CLEAN, YOUR WAY</div><h2>Know the direction<br/><i>before you book.</i></h2><p>Use this quick estimate to understand the starting point. Final pricing can be connected to approved service-area rules, home details and add-ons.</p><div className="quoteChecks"><span><Check/> Clear pricing guidance</span><span><Check/> Flexible service options</span><span><Check/> Easy booking journey</span></div></div></Reveal><Reveal delay={100}><div className="quoteCard"><div className="quoteTitle"><span>01</span><div><b>Start your estimate</b><small>Tell us about your home</small></div></div><label>HOME TYPE</label><div className="selectRow">{['House','Apartment','Condo'].map(x=><button className={home===x?'selected':''} key={x} onClick={()=>setHome(x)}><HomeIcon size={16}/> {x}</button>)}</div><div className="fieldGrid"><label>BEDROOMS<select value={beds} onChange={e=>setBeds(e.target.value)}><option value="1">1 bedroom</option><option value="2">2 bedrooms</option><option value="3">3 bedrooms</option><option value="4">4+ bedrooms</option></select></label><label>BATHROOMS<select value={baths} onChange={e=>setBaths(e.target.value)}><option value="1">1 bathroom</option><option value="2">2 bathrooms</option><option value="3">3 bathrooms</option><option value="4">4+ bathrooms</option></select></label></div><label>HOW OFTEN?<select value={freq} onChange={e=>setFreq(e.target.value)}><option>One time</option><option>Weekly</option><option>Biweekly</option><option>Monthly</option></select></label><div className="priceCard" style={{marginTop:18,background:'var(--sage2)'}}><small>PLANNING ESTIMATE</small><strong>${estimate}</strong><small>Starting estimate • final quote depends on confirmed details</small></div><a className="fullBtn" href="/book">Continue to booking <ArrowRight size={18}/></a><small className="quoteNote"><ShieldCheck size={16}/> No payment required to request a quote.</small></div></Reveal></section>
 <Reveal><section className="split section"><div className="splitImg"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85" alt="Beautiful clean home interior"/></div><div className="splitCopy"><div className="sectionLabel">WHY LUMIÈRE</div><h2>A clean home.<br/><i>A lighter life.</i></h2><p>From everyday upkeep to detailed resets, the experience is designed around consistency, care and a clear customer journey.</p><div className="feature"><ShieldCheck/><div><h3>Trust-led from the start</h3><p>Clear service paths, communication and booking expectations.</p></div></div><div className="feature"><Sparkles/><div><h3>Details worth noticing</h3><p>Thoughtful attention across kitchens, bathrooms, bedrooms and living spaces.</p></div></div><div className="feature"><HeartHandshake/><div><h3>Made to feel personal</h3><p>Choose frequency, priorities and service type around your home.</p></div></div><a className="textLink" href="/about">Meet Lumière <ArrowRight size={18}/></a></div></section></Reveal>
 <section className="process section"><Reveal><div className="centerHead"><div className="sectionLabel">HOW IT WORKS</div><h2>Simple from <i>start to finish.</i></h2><p>A clear journey from your first quote request to a home that feels refreshed.</p></div></Reveal><div className="steps">{[[CalendarDays,'Choose your service','Select the cleaning service, home details, frequency and add-ons that fit your needs.'],[Clock3,'Pick a time','Choose your preferred date and time through the booking journey.'],[Sparkles,'Enjoy your clean','Receive confirmation and reminders, then come home to a refreshed space.']].map(([I,t,p],i)=><Reveal key={t} delay={i*100}><div><span>0{i+1}</span><I/><h3>{t}</h3><p>{p}</p></div></Reveal>)}</div></section>
 <section className="visualBreak"><Reveal><div><div className="sectionLabel light">THE LITTLE THINGS MATTER</div><h2>Your space deserves<br/><i>to feel cared for.</i></h2><a className="btn gold" href="/book">Start with a quote <ArrowRight size={18}/></a></div></Reveal></section>
 <section className="reviews section"><Reveal><div className="sectionTop"><div><div className="sectionLabel">CUSTOMER STORIES</div><h2>Good service<br/><i>speaks for itself.</i></h2></div><div className="reviewScore"><span className="stars">★★★★★</span><b>Premium</b><small>Customer experience focus</small></div></div></Reveal><div className="reviewGrid">{['The kind of clean that makes you want to stay home. Everything felt fresh, organized and beautifully finished.','Easy communication, thoughtful service and a home that felt completely reset.','From the first enquiry to the finished clean, the whole experience felt professional and simple.'].map((t,i)=><Reveal key={t} delay={i*90}><blockquote>“{t}”<footer><b>Customer story</b><span>Sample presentation for approved reviews</span></footer></blockquote></Reveal>)}</div></section>
 <section className="areas section"><Reveal><div className="areaBox"><MapPin size={22}/><div><div className="sectionLabel light">SERVICE AREAS</div><h2>Is Lumière <i>near you?</i></h2><p>Enter your ZIP/postal code to preview the service-area check.</p><div className="zip"><input value={zip} onChange={e=>setZip(e.target.value.replace(/\D/g,'').slice(0,5))} placeholder="Enter ZIP code" inputMode="numeric"/><button onClick={()=>notify(zip.length===5?'Coverage request captured — connect approved service-area rules next.':'Please enter a 5-digit ZIP code.')}>Check coverage <ArrowRight size={17}/></button></div></div></div></Reveal></section>
 <section className="faq section"><Reveal><div className="sectionTop"><div><div className="sectionLabel">FAQ</div><h2>Questions, <i>answered.</i></h2></div><p>Clear information before you book means a smoother experience from the start.</p></div></Reveal><div className="faqGrid">{faqs.map((f,i)=><div className={faq===i?'faqItem active':'faqItem'} key={f[0]}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{f[0]}</span><ChevronDown/></button>{faq===i&&<p>{f[1]}</p>}</div>)}</div></section>
 <section className="finalCta"><Reveal><div><div className="sectionLabel light">READY WHEN YOU ARE</div><h2>Let’s give your home<br/><i>the care it deserves.</i></h2><p>Request a quote, ask a question, or start planning your next clean.</p><div className="ctaBtns"><a className="btn gold" href="/book">Get an Instant Quote <ArrowRight size={18}/></a><a className="btn ghost" href="tel:+10000000000"><Phone size={18}/> Call Us</a></div></div></Reveal></section>
 </main>
}
